version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    command: spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - <path_to_local_clone_of_repo>:/app/data
    environment:
      # Replace with your actual OpenCage API key
      - OPENCAGE_API_KEY=<your_opencage_api_key>

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    command: spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
